# Generated by Django 3.1.2 on 2021-04-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userc',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
