# Generated by Django 3.1.2 on 2021-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210604_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userc',
            name='profile_img',
            field=models.ImageField(default='pm/dd046c1f-b99.png', null=True, upload_to='pm'),
        ),
    ]
