# Generated by Django 3.1.2 on 2021-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210608_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='background_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='logo_outline',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userc',
            name='profile_img',
            field=models.ImageField(default='pm/dd046c1f-b99.png', null=True, upload_to=''),
        ),
    ]
