# Generated by Django 3.1.2 on 2021-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210707_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userc',
            name='profile_img',
            field=models.ImageField(default='136-1360754_overwatch-wallpaper-hd-genji-fan-art-overwatch.jpg', null=True, upload_to=''),
        ),
    ]
