# Generated by Django 3.1.2 on 2021-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210709_1334'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userc',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userc',
            name='profile_img',
            field=models.ImageField(default='test.jpg', null=True, upload_to=''),
        ),
    ]
