# Generated by Django 3.1.2 on 2021-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211013_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userc',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
