# Generated by Django 3.1.2 on 2022-02-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_ticketorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='text_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
