# Generated by Django 3.1.2 on 2022-02-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220208_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
