# Generated by Django 3.1.2 on 2022-02-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220208_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
