# Generated by Django 3.1.2 on 2021-03-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210210_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='url',
        ),
    ]
