# Generated by Django 3.1.2 on 2021-03-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210317_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.article'),
        ),
    ]
