# Generated by Django 3.1.2 on 2021-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210322_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='pm'),
        ),
    ]
