# Generated by Django 3.1.2 on 2021-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
