# Generated by Django 3.1.2 on 2021-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_article_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='points',
        ),
    ]
