# Generated by Django 3.1.2 on 2021-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20210420_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
