# Generated by Django 3.1.2 on 2021-04-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city_country', '0001_initial'),
        ('mainpage', '0014_auto_20210422_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='post_cities', to='city_country.City'),
        ),
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='post_countries', to='city_country.Country'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='mainpage.Tag', verbose_name='Теги'),
        ),
    ]
