# Generated by Django 3.1.2 on 2021-06-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
