# Generated by Django 3.1.2 on 2021-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_delete_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
