# Generated by Django 3.1.2 on 2021-07-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='article',
            new_name='post',
        ),
    ]
