# Generated by Django 3.1.2 on 2021-07-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_auto_20210727_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='lng',
        ),
    ]
