# Generated by Django 3.1.2 on 2021-08-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20210728_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lenta',
        ),
        migrations.RemoveField(
            model_name='article',
            name='simple',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upd',
        ),
    ]
