# Generated by Django 3.1.2 on 2021-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
