# Generated by Django 3.1.2 on 2021-02-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210210_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_c', to='comment.comment'),
        ),
    ]
