# Generated by Django 3.1.2 on 2021-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='pm'),
        ),
    ]
