# Generated by Django 3.1.2 on 2021-04-05 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0006_auto_20210405_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorofcomment', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
